source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
install! 'cocoapods', integrate_targets: false
#use_frameworks!

target 'FacebookAdapter' do
   pod 'Google-Mobile-Ads-SDK', '~> 7.53.1'
   pod 'FBAudienceNetwork', '~> 5.6.0'
end
