source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
install! 'cocoapods', integrate_targets: false
#use_frameworks!

target 'UnityAdapter' do
   pod 'Google-Mobile-Ads-SDK', '~> 7.55.0'
   pod 'UnityAds', '~> 3.4.2'
end
