source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
install! 'cocoapods', integrate_targets: false
#use_frameworks!

target 'AppLovinAdapter' do
   pod 'Google-Mobile-Ads-SDK', '~> 7.55.0'
   pod 'AppLovinSDK', '~> 6.11.3'
end
