source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
install! 'cocoapods', integrate_targets: false
#use_frameworks!

target 'MoPubAdapter' do
   pod 'Google-Mobile-Ads-SDK', '~> 7.61.0'
   pod 'mopub-ios-sdk/Core', '5.11.0'
end
