source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
install! 'cocoapods', integrate_targets: false
#use_frameworks!

target 'MoPubAdapter' do
   pod 'Google-Mobile-Ads-SDK', '~> 7.53.1'
   pod 'mopub-ios-sdk/Core', '5.8.0'
end
